### ISSUE TITLE
server crash during connection

### ISSUE THREAD

**Issue by Harybo** [Dislaik/outbreak#4]
Hello,

as soon as I try to connect to my server, it crashes

![image](https://user-images.githubusercontent.com/29784405/97001385-965d9780-1538-11eb-8048-9e2619d32978.png)

![image](https://user-images.githubusercontent.com/29784405/97001534-cc028080-1538-11eb-9fa5-e5747e0347fd.png)

**Comment by Dislaik** [comment]
I couldn't tell you what exactly causes this, you can give more information about your server? did you follow the steps in [README.MD](https://github.com/Dislaik/outbreak/blob/master/README.md)?

**Comment by Harybo** [comment]
I followed the steps as instructed. The server only has the indicated resources ensure
