### ISSUE TITLE
Little Error

### ISSUE THREAD

**Issue by chopo156** [Dislaik/outbreak#5]
Impresionante resource dejame decirte, solo que tengo este drama cuando inicio, creo que tiene algo que ver con el inventario. (los errores de C# en Fivem son en arameo)
https://prnt.sc/vcx361

**Comment by Dislaik** [comment]
Most probably, you are trying to occupy a weapon that you have not registered in the database, the next version will have exceptions so the framework does not fall, do the aforementioned and tell me how you're doing
